services:
  handler:
    build:
      context: .
      target: handler
    restart: unless-stopped
    container_name: handler
    tty: true
    env_file:
      - .env
    depends_on:
      cache:
        condition: service_started
      database-setup:
        condition: service_completed_successfully

  gateway:
    build:
      context: .
      target: gateway
    restart: unless-stopped
    container_name: gateway
    tty: true
    env_file:
      - .env
    depends_on:
      cache:
        condition: service_started
      database-setup:
        condition: service_completed_successfully

  database-setup:
    build:
      context: .
      target: database-setup
    restart: "no"
    container_name: setup
    tty: true
    env_file:
      - .env
    depends_on:
      database:
        condition: service_started

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "8080:8080"
    tty: true
    env_file:
      - .env
  
  cache:
    container_name: cache
    image: eqalpha/keydb:alpine
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - cache-data:/data
      - ./config/cache/keydb.conf:/etc/keydb/keydb.conf
  
  database:
    container_name: database
    image: postgres:alpine
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
      
volumes:
  cache-data:
  database-data: